erro
Plotting barcode04...
Traceback (most recent call last):
  File "/mnt/e/Data/seq_for_human_293t2/barcode04/comethylation_analy.py", line 406, in <module>
    plt.savefig(os.path.join(out_dir, f'{sample_name}_methylation_density.png'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/pyplot.py", line 1250, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/figure.py", line 3490, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2157, in print_figure
    self.figure.draw(renderer)
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/artist.py", line 94, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/artist.py", line 71, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/figure.py", line 3257, in draw
    mimage._draw_list_compositing_images(
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/image.py", line 134, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/artist.py", line 71, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 3226, in draw
    mimage._draw_list_compositing_images(
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/image.py", line 134, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/e/venvs/seq_env/lib/python3.12/site-packages/matplotlib/artist.py", line 71, in draw_wrapper
